modulo04/core/urls.py
# core/urls.py
from django.urls import path
from . import views
from .views import contagem_tarefas,duplicar_tarefa

urlpatterns = [
    path('home/', views.home, name='home'),
    path('tarefa/<int:pk>/concluir/', views.concluir_tarefa, name='concluir_tarefa'),
    path('tarefa/<int:pk>/deletar/', views.deletar_tarefa, name='deletar_tarefa'),
    path('register/', views.register, name='register'),
    path('tarefas/contagem/', contagem_tarefas, name='contagem-tarefas'),
    path('tarefas/<int:tarefa_id>/duplicar/', duplicar_tarefa, name='duplicar_tarefa'),
]

modulo04/meuprojeto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include('core.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'),name='logout'),
    path('projects/', include('projects.urls')),
    
]

modulo04/projects/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path("adicionar-projeto/", views.adicionar_projeto, name= "adicionar_projeto"),
]

modulo04/core/models.py
from django.db import models
from django.contrib.auth.models import User
from projects.models import Project
from django.core.exceptions import ValidationError
from django.utils import timezone


class Tarefa(models.Model):
    
    
    user = models.ForeignKey(User, on_delete=models.CASCADE) 
    
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='tarefas')
    
    titulo = models.CharField(max_length=200)
    
    descricao=models.TextField(blank=True)
   
    concluida = models.BooleanField(default=False)
    
    criada_em = models.DateTimeField(auto_now_add=True)
    
    PRIORIDADE_CHOICES = [
        ('baixa', 'Baixa'),
        ('media', 'Média'),
        ('alta', 'Alta'),
    ]

    
    prioridade = models.CharField(
        max_length=5,
        choices=PRIORIDADE_CHOICES,
        default='media'
    )

    prazo = models.DateField(null=False, blank=False)
    
    data_conclusao = models.DateTimeField(
        null=True,
        blank=True
    )
    
    def clean(self):
        if self.prazo and self.prazo < timezone.now().date():
            raise ValidationError({
                'prazo': 'O prazo não pode ser uma data no passado.'
            })
            
            
    def save(self, *args, **kwargs):
        if self.concluida and self.data_conclusao is None:
            self.data_conclusao = timezone.now()
        if not self.concluida:
            self.data_conclusao = None

        super().save(*args, **kwargs)
        

  
    def __str__(self):
        return self.titulo

modulo04/projects/models.py
from django.db import models
from django.contrib.auth.models import User

class Project(models.Model):
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=100)
    
    
    def __str__(self):
        return self.titulo

modulo04/core/forms.py
from django import forms
from .models import Tarefa 
from projects.models import Project

class TarefaForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):

        user = kwargs.pop('user', None)

        super(TarefaForm, self).__init__(*args, **kwargs)

        if user:

            self.fields['project'].queryset = Project.objects.filter(user=user)

    class Meta:
        model = Tarefa
        fields = ['titulo','descricao','project', 'prazo','prioridade','concluida']
        widgets = {
            'prazo': forms.DateInput(attrs={'type': 'date'})
        }

modulo04/projects/forms.py
from django import forms
from .models import Project

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields =['titulo']

modulo04/core/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from .models import Tarefa
from .forms import TarefaForm
from django.contrib import messages 
from django.http import JsonResponse, HttpResponseNotAllowed



@login_required
def home(request):

    if request.method== 'POST':
        
        form = TarefaForm(request.POST, user=request.user)
        
        if form.is_valid():

            tarefa = form.save(commit=False) 
            tarefa.user = request.user 
            tarefa.full_clean()
            tarefa.save()
            
            return redirect('home')
    
    else:
        
        form = TarefaForm(user=request.user)



    
    todas_as_tarefas=Tarefa.objects.filter(user=request.user).order_by('-criada_em')

    context={
        'nome_usuario':request.user.username,
        'tecnologias': ['Autenticação','ForeignKey','Login','HTML','CSS','Django','SQL','Banco de Dados'],
        'tarefas': todas_as_tarefas,
        'form': form,
    }
    
    return render(request, 'home.html', context)

@login_required
def concluir_tarefa(request, pk):

    tarefa = get_object_or_404(Tarefa, pk=pk, user=request.user)

    if request.method == 'POST':

        if not tarefa.concluida:
            tarefa.concluida = True
            tarefa.save()
            messages.success(request, "Parabéns! Tarefa concluida com sucesso!")
        else:
       
            tarefa.concluida = False
            tarefa.save()
            messages.warning(request,"Tarefa marcada como pendente")
           

        return redirect('home')

@login_required    
def deletar_tarefa(request, pk):

    tarefa = get_object_or_404(Tarefa, pk=pk,user=request.user)

    if request.method == 'POST':

        tarefa.delete()
        return redirect('home')

def register(request): 

    if request.method == 'POST': 

        form = UserCreationForm(request.POST) 

        if form.is_valid(): 
            user = form.save() 
            login(request, user) 
            return redirect('home') 
 
    else: 
        form = UserCreationForm() 

    context = {'form': form}
    return render(request, 'register.html', context)

def contagem_tarefas(request):
    total = Tarefa.objects.count()
    concluidas = Tarefa.objects.filter(concluida=True).count()
    pendentes = Tarefa.objects.filter(concluida=False).count()

    return JsonResponse({
        "total": total,
        "concluidas": concluidas,
        "pendentes": pendentes
    })
    
def duplicar_tarefa(request, tarefa_id):
    if request.method != 'POST':
        return HttpResponseNotAllowed(['POST'])

    try:
        tarefa = Tarefa.objects.get(id=tarefa_id)
    except Tarefa.DoesNotExist:
        return JsonResponse(
            {"erro": "Tarefa não encontrada"},
            status=404
        )

    nova_tarefa = Tarefa.objects.create(
        titulo=f"{tarefa.titulo} (Cópia)",
        descricao=tarefa.descricao,
        prioridade=tarefa.prioridade,
        prazo=tarefa.prazo,
        concluida=False
    )

    return JsonResponse({
        "mensagem": "Tarefa duplicada com sucesso",
        "nova_tarefa_id": nova_tarefa.id
    }, status=201)
    
    
def lista_tarefas(request):
    tarefas = Tarefa.objects.all()
    return render(request, 'tarefas/lista.html', {'tarefas': tarefas})        

modulo04/projects/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Project
from .forms import ProjectForm
from django.contrib.auth.decorators import login_required

@login_required
def adicionar_projeto(request):
    if request.method == "POST":
        form = ProjectForm(request.POST)
        if form.is_valid():
            projeto= form.save(commit=False)
            projeto.user= request.user
            projeto.save()
            messages.success(request, "Projeto criado com sucesso!", extra_tags="concluida")
            return redirect("home")
    else:
        form = ProjectForm()

    return render(request, "adicionar_projeto.html", {"form": form})

modulo04/templates/adicionar_projeto.html
{% extends 'base.html' %}

{% block title %}Adicionar Projeto{% endblock %}

{% block content %}
<div class="card">
    <h2 class="subtitle">Adicionar Novo Projeto</h2>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn-primary">Salvar Projeto</button>
    </form>
</div>
{% endblock %}

modulo04/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} Meu Site Django {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>

<body>
    <header class="navbar-fixed">
        <nav >
            <a href="{% url 'home' %}">Home</a>

            {% if user.is_authenticated %}
            <span>Olá, {{ user.username }}!</span>

            <form action="{% url 'logout' %}" method="POST" class="logout-form">
                {% csrf_token %}
                <button type="submit" class="logout-btn">
                    SAIR
                </button>
            </form>

            {% else %}
            <a href="{% url 'login' %}">Entrar</a>
            <a href="{% url 'register' %}">Cadastre-se</a>
            {% endif %}
        </nav>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer>
        <p>© 2025 - Meu Site Incrível</p>
    </footer>
</body>

</html>

modulo04/templates/home.html
{% extends 'base.html' %}

{% block title %}
Página Inicial - Meu Site
{% endblock %}

{% block content %}
{% if messages %}
  <div class="messages">
    {% for message in messages %}
      <div class="message {{ message.tags }}">{{ message }}</div>
    {% endfor %}
  </div>
{% endif %}
<h1 class="title">Olá, {{ user.username }}!</h1>

<div class="card">
  <h3 class="subtitle">Nova Tarefa</h3>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn-primary">Adicionar Tarefa</button>
  </form>
</div>

<div class="card">
  <h3 class="subtitle">Novo Projeto</h3>
  {% if user.is_authenticated %}
  <form action ="{% url 'adicionar_projeto'%}" method="get">
    <button type="submit" class="btn-primary">Adicionar Projeto</button>
      </form>
  {% else %}
      <p class="empty-message">Você precisa estar logado para adicionar projetos.</p>
  {% endif %}
</div>
</div>
  <h3 class="subtitle">Tecnologias que estou aprendendo</h3>
  {% if tecnologias %}
  <ul class="tech-list">
    {% for tecnologia in tecnologias %}
    <li class="tech-item">{{ tecnologia }}</li>
    {% endfor %}
  </ul>
  {% else %}
  <p class="empty-message">Você não está aprendendo nenhuma tecnologia no momento.</p>
  {% endif %}
</div>


<div class="card">
  <h2 class="subtitle">Minha Lista de Tarefas</h2>

  {% if tarefas %}
  {% for tarefa in tarefas %}
  <div class="task-card">

    <p class="task-project">Projeto: <strong>{{ tarefa.project.titulo }}</strong></p>

    <p class="task-title">
  <strong>{{ tarefa.titulo }}</strong>
</p>

{% if tarefa.descricao %}
<p class="task-desc">
  {{ tarefa.descricao }}
</p>
{% endif %}

<p class="task-info">
  Prioridade: <strong>{{ tarefa.get_prioridade_display }}</strong><br>
  Prazo: <strong>{{ tarefa.prazo|date:"d/m/Y" }}</strong>
</p>

<p class="task-status">
  {% if tarefa.concluida %}
    <span class="status-concluida">
      ✔ Concluída em {{ tarefa.data_conclusao|date:"d/m/Y H:i" }}
    </span>
  {% else %}
    <span class="status-pendente">☐ Pendente</span>
  {% endif %}
</p>

<small class="task-date">
  Criada em: {{ tarefa.criada_em|date:'d/m/Y H:i' }}
</small>

    <div style="margin-top: 10px;">

  <form action="{% url 'deletar_tarefa' tarefa.pk %}" method="POST" style="display: inline;">
    {% csrf_token %}
    <button type="submit" class="btn btn-delete">Deletar</button>
  </form>

  <form action="{% url 'duplicar_tarefa' tarefa.pk %}" method="POST" style="display: inline;">
    {% csrf_token %}
    <button type="submit" class="btn btn-duplicar">Duplicar</button>
  </form>

  {% if not tarefa.concluida %}
  <form action="{% url 'concluir_tarefa' tarefa.pk %}" method="POST" style="display: inline;">
    {% csrf_token %}
    <button type="submit" class="btn btn-concluir">Marcar como Concluída</button>
  </form>
  {% endif %}

  {% if tarefa.concluida %}
  <form action="{% url 'concluir_tarefa' tarefa.pk %}" method="POST" style="display: inline;">
    {% csrf_token %}
    <button type="submit" class="btn btn-pendente">Marcar como Pendente</button>
  </form>
  {% endif %}

</div>

    </div>

  </div>
  {% endfor %}
  {% else %}
  <p class="empty-message">Você ainda não tem tarefas cadastradas.</p>
  {% endif %}
</div>

{% endblock %}

modulo04/templates/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}

{% block content %}
<h2>Login</h2>
{% if form.errors %}
<p style="color: red;">Seu usuário ou senha estão incorretos. Tente
    novamente.</p>  
{% endif %}
<form method="POST" action="{% url 'login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Entrar</button>
</form>
<p><a href="{% url 'register' %}">Não tem uma conta? Cadastre-se</a></p>

{% endblock %}

modulo04/templates/register.html
{% extends 'base.html' %}
{% block title %}Cadastro{% endblock %}
{% block content %}

<h2>Cadastre-se</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar Conta</button>
</form>
{% endblock %}